### ISSUE TITLE
Table results?

### ISSUE THREAD

**Issue by subetter** [lxd99/CTCP#3]
Dear author,
In your work you have compared a variety of advanced methods, but why is the data in your table different from the data presented in the original paper under the same Settings? Can you explain how you got the data for your table?
Sincerely

**Comment by lxd99** [comment]
Thanks for your question. Please note that, although under the same experimental setting, the performance of a model can vary due to differences in the environment (e.g., python package version and hardware). Specifically, throughout the experiment, certain operations involve randomness, and these variations in the environment can lead to divergent results and different model performances.  We list some of such operations as follows.
1) The selection of the training, validating, and testing cascades is random. Our selection may not be the same as the original paper.
2) The model initialization is random, our initialization may not be the same as the original paper.
3)  The result of the dropout layer is random.
